config/routes.rb
Rails.application.routes.draw do
  unless Rails.env.development?
    get "/service-worker.js", to: "pwa#service_worker", as: :pwa_service_worker
    get "/manifest.json", to: "pwa#manifest", as: :pwa_manifest
  end

  passwordless_for :guests
  resources :guests

  get "RSVP", to: "parties#new" # in case of all caps
  get "rsvp", to: "parties#new", as: :new_party
  get "rsvp/step-2(/:id)", to: "parties#onboarding", as: :onboarding
  resource :party, except: [:new, :index, :destroy]
  resources :guilds, only: [:index, :show]

  get "registry", to: "infos#registry", as: :registry

  get "realm", to: "infos#map", as: :map
  get "map", to: "infos#map" # just in case people try it
  resources :locations, only: [:index]

  namespace :dungeon_master, path: "dm" do
    resources :parties
    resources :guilds
    resources :quests
    resources :guests
    resources :locations
    resources :mailings, only: [:index, :new, :show, :create]
    root "guests#index"
  end

  root "infos#home"
end

app/models/party.rb
class Party < ApplicationRecord
  validates :rsvp, inclusion: [true, false]

  has_many :guests, dependent: :destroy
  accepts_nested_attributes_for :guests
  validate :guests_preferences_are_present

  normalizes :notes, with: ->(notes) { notes.strip }

  normalizes :name, with: ->(name) { name.strip }
  before_validation :set_default_name, unless: :name?
  validates :name, presence: true, uniqueness: {case_sensitive: false}

  before_validation :set_deadline
  validates :response_deadline, presence: true

  def locked?
    Date.today > response_deadline
  end

  private

  def set_default_name
    self.name ||= "#{guests.first.name}’s Party" if guests.first
  end

  def set_deadline
    self.response_deadline ||= Date.today.end_of_month
  end

  def guests_preferences_are_present
    return unless persisted?
    return unless rsvp

    guests.each do |guest|
      unless guest.food_preference.present?
        errors.add(:guests, "must all have chosen a feast")
      end

      unless guest.guild_id.present?
        errors.add(:guests, "must all have chosen a guild")
      end
    end
  end
end

app/controllers/dungeon_master/parties_controller.rb
class DungeonMaster::PartiesController < PartiesController
  include DungeonMaster::Cerberus
  before_action :set_party, only: [:show, :edit, :update, :destroy]

  def index
    @parties = Party.all
    @attending = Guest.attending
  end

  def show
  end

  def edit
  end

  def update
    if @party.update(party_params)
      redirect_to [:dungeon_master, @party], notice: "Party was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @party.destroy
    redirect_to [:dungeon_master, @party]
  end

  private

  def set_party
    @party = Party.find(params[:id])
  end

  def party_params
    params.require(:party).permit(
      :name,
      :rsvp,
      :notes,
      :response_deadline,
      guests_attributes: [
        :id,
        :name,
        :email,
        :under_13,
        :food_preference,
        :notes
      ]
    )
  end
end

app/controllers/parties_controller.rb
class PartiesController < ApplicationController
  # before_action :redirect_because_rsvps_are_closed, only: [:new, :create, :onboarding]

  before_action :require_user!, except: [:new, :create]
  before_action :set_user_party, only: [:edit, :update, :onboarding, :show]

  def show
    @og_image = "og-party.jpg"
  end

  def new
    redirect_to onboarding_path if current_user
    @party = Party.new
    @party.guests.build
  end

  def create
    @party = Party.new(party_params)

    # before we attempt to save, check if this is someone trying to login
    if Guest.exists?(email: @party.guests.first.email)
      redirect_to onboarding_path and return
    end

    if @party.save
      sign_in(create_passwordless_session(@party.guests.first)) unless current_user&.dungeon_master?

      redirect_to onboarding_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def onboarding
    if @party.rsvp
      @additional_guests = @party.guests.reject { |guest| guest == current_user }
    else
      render :declined
    end
  end

  def edit
    redirect_to onboarding_path
  end

  def update
    if @party.update(party_params)
      redirect_to party_path(@party)
      notify_dms
    else
      render_referrer = request.referer&.include?(onboarding_path) ? :onboarding : :edit
      render render_referrer, status: :unprocessable_entity
    end
  end

  private

  def redirect_because_rsvps_are_closed
    flash[:notice] = "RSVPs are closed!"

    if current_user
      redirect_to party_path
    else
      redirect_to root_path
    end
  end

  def set_user_party
    @party ||= current_user.party
  end

  def validate_guest_preferences
    @party.guests.each(&:validate_preferences)
  end

  def notify_dms
    guest_list = []

    if @party.rsvp
      @party.guests.each do |guest|
        guest_list << "- #{guest.name} (#{guest.feast}, #{guest.guild.name})"
      end
    end

    DungeonMasterNotifier.notify(
      "#{@party.guests.first.name} responded!",
      <<~BODY
        #{@party.name} rsvp'd '#{@party.rsvp ? "accept" : "can’t make it"}'.

        #{guest_list.join("\n")}

        DM Screen: #{dungeon_master_root_url}
        Email them: #{@party.guests.first.email}
      BODY
    )
  end

  def party_params
    params.require(:party).permit(
      :name,
      :rsvp,
      :notes,
      guests_attributes: [
        :id,
        :name,
        :email,
        :under_13,
        :food_preference,
        :notes
      ]
    )
  end
end

app/helpers/dungeon_master/parties_helper.rb
module DungeonMaster::PartiesHelper
end

app/helpers/parties_helper.rb
module PartiesHelper
end

app/views/parties/_add_guests.html.erb
<%= turbo_frame_tag "new_guest_for_#{dom_id(party)}", class: "contents" do %>
<% end %>

<div class="flex flex-col justify-start align-baseline text-red-800 text-left italic rounded border border-red-900/40 border-dashed divide-y divide-red-900/40 divide-dashed">
  <%= link_to "+ Add guest (age 13+)", new_guest_path(party_id: party.id), data: { turbo_frame: "new_guest_for_#{dom_id(party)}" }, class: "p-2 grid place-content-center hover:bg-red-700/5 hover:shadow-inner hover:text-red-950 hover:underline transition-all" %>
  <%= link_to "+ Add child (under age 13)", new_guest_path(under_13: true, party_id: party.id), data: { turbo_frame: "new_guest_for_#{dom_id(party)}" }, class: "p-2 grid place-content-center hover:bg-red-700/5 hover:shadow-inner hover:text-red-950 hover:underline transition-all" %>
</div>

app/views/parties/_party.html.erb
<% hide_controls = local_assigns.fetch(:hide_controls, false) %>
<% guest_collection = local_assigns[:guests] || party.guests %>

<div class="flex flex-col gap-3">
  <%= turbo_frame_tag "#{dom_id(party)}_guests", class: "contents" do %>
    <%= render partial: "guests/guest", collection: guest_collection, as: :guest %>
  <% end %>

  <% if !hide_controls && !party.locked? && (party == current_user.party || current_user.dungeon_master?) %>
    <%= render partial: "add_guests", locals: {party: party} %>
  <% end %>
</div>

app/views/parties/declined.html.erb
<div class="bg-cover bg-[url('backgrounds/forest.jpg')] bg-fixed min-h-screen p-4 md:p-12 xl:p-20">
  <%= form_for @party, data: { turbo_frame: "_top" } do |f| %>
    <section class="grid">
      <div class="mx-auto card bg-paper max-w-screen-sm w-full space-y-4">
        <div class="space-y-1">
          <h2>We will miss you!</h2>
          <p>Your presence will be missed, but we understand and appreciate your response.</p>
        </div>
        <div class="field">
          <%= f.label :notes, "Optional" %>
          <%= f.text_area :notes, rows: 6, placeholder: "Send a message to Nick & Marnie" %>
        </div>
        <div class="flex max-sm:flex-col gap-4 justify-between items-baseline">
          <%= f.submit "Send message", class: "btn primary max-sm:self-stretch" %>
          <%= render "shared/quick_links" %>
        </div>
      </div>
    </section>
  <% end %>
</div>

app/views/parties/new.html.erb
<div class="bg-cover bg-[url('backgrounds/forest.jpg')] bg-fixed min-h-screen p-4">
  <div class="my-80 md:my-12">
    <section class="text-center space-y-6 card bg-paper max-w-screen-sm mx-auto pt-4 md:pt-8 pb-12 -rotate-[0.5deg]">
      <%= image_tag "props/seal.png", class: "size-24 block mx-auto -mt-6" %>
      <div class="space-y-1">
        <h2>Dearest friends &amp; family, from far and wide</h2>
        <p>Your assistance is requested in a matter most close to heart:</p>
      </div>
      <div class="space-y-1">
        <h3 class="uppercase text md:text-xl font-normal">the next chapter for</h3>
        <h1 class="text-5xl">Marnie Williams &amp; Nick Noble</h1>
        <h3 class="uppercase text md:text-xl font-normal">starts on April 28th, 2024</h3>
      </div>
    </section>
    <section class="text-center space-y-6 card  bg-paper max-w-[32ch] mx-auto -mt-8 rotate-[0.5deg]">
      <%= form_for @party, url: party_path do |f| %>
        <div class="grid gap-4">
          <% if @party.errors.any? %>
            <div class="text-red-700 border border-current p-2" id="error_explanation">
              <h4><%= pluralize(@party.errors.count, "error") %> prohibited this party from being saved:</h4>
              <ul>
                <% @party.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>
          <div class="rsvp-question text-emerald-800">
            <%= f.label :rsvp, "Will you aid our quest?", class: "block text-lg font-bold italic tracking-tight -mt-1" %>
            <div class="inline-block text-left mx-auto">
              <%= f.label :rsvp_true, class: "block" do %>
                <%= f.radio_button :rsvp, true, required: true %>
                Accept the call
              <% end %>
              <%= f.label :rsvp_false, class: "block" do %>
                <%= f.radio_button :rsvp, false, required: true %>
                Regretfully decline
              <% end %>
            </div>
          </div>
          <%= f.fields_for :guests do |g| %>
            <% if g.object.errors.any? %>
              <div class="text-red-700 border border-current p-2">
                <h4><%= pluralize(g.object.errors.count, "error") %> prevented this from submitting:</h4>
                <ul>
                  <% g.object.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>
            <div class="flex flex-col boxed text-left">
              <div class="field">
                <%= g.label :name, "Your name" %>
                <%= g.text_field :name, required: true %>
              </div>
              <div class="field border-t-0">
                <%= g.label :email, "Your email" %>
                <%= g.email_field :email, required: true %>
              </div>
            </div>

            <p class="italic leading-tight">There will be space to add additional guests on the following page.</p>
          <% end %>
          <div class="text-center">
            <%= f.submit "Next &rarr;".html_safe, class: "btn" %>
          </div>
        </div>
      <% end %>
    </section>
  </div>
</div>

app/views/parties/onboarding.html.erb
<div class="bg-cover bg-[url('backgrounds/forest.jpg')] bg-fixed min-h-screen p-4 md:p-12 xl:p-20">
  <div class="flex flex-col gap-12 max-w-screen-xl mx-auto relative z-10">
    <% if @party.guests.include? current_user # don't confuse dungeon_masters %>
      <section class="grid flex-col gap-4 card bg-paper max-w-screen-md odd:-rotate-[0.5deg] even:rotate-[0.5deg] even:self-end">
        <div class="space-y-1 text-center">
          <h2>There will be a glorious feast</h2>
          <p>But in order to prepare, we must know what you would like to dine on:</p>
        </div>
        <%= form_for current_user, data: {
            controller: "form",
            action: "input->form#submit"
          } do |f| %>
          <div class="grid md:grid-cols-3 gap-1 *:px-1 italic">
            <%= f.label :food_preference_vegetarian, class: "block max-sm:w-40 mx-auto text-center pt-1 px-1 has-[:checked]:bg-gold" do %>
              <%= f.radio_button :food_preference, 'vegetarian', class: "sr-only peer" %>
              <%= image_tag('food/vegetarian.jpg', alt: 'Vegetarian', title: 'Vegetarian', class: "rounded-sm border-[1.5px] border-amber-950/50" ) %>
              <span class="peer-checked:text-white peer-checked:font-bold">Foraged</span>
            <% end %>
            <%= f.label :food_preference_duck, class: "block max-sm:w-40 mx-auto text-center pt-1 px-1 has-[:checked]:bg-gold" do %>
              <%= f.radio_button :food_preference, 'duck', class: "sr-only peer" %>
              <%= image_tag('food/duck.jpg', alt: 'Duck', title: 'Duck', class: "rounded-sm border-[1.5px] border-amber-950/50" ) %>
              <span class="peer-checked:text-white peer-checked:font-bold">Fowl</span>
            <% end %>
            <%= f.label :food_preference_salmon, class: "block max-sm:w-40 mx-auto text-center pt-1 px-1 has-[:checked]:bg-gold" do %>
              <%= f.radio_button :food_preference, 'salmon', class: "sr-only peer" %>
              <%= image_tag('food/salmon.jpg', alt: 'Salmon', title: 'Salmon', class: "rounded-sm border-[1.5px] border-amber-950/50" ) %>
              <span class="peer-checked:text-white peer-checked:font-bold">Fish</span>
            <% end %>
          </div>
        <% end %>
        <hr/>
        <div class="md:grid grid-cols-3 gap-4 md:items-center max-w-md mx-auto">
          <%= image_tag "food/tea-b.jpg", class: "max-md:float-left max-md:size-24 max-md:mr-2 max-size-48 aspect-square rounded border border-amber-950/50", alt: "An oil painting of a magical cup of black tea in a beautiful porcelain china teacup nestled in the underbrush of a fantasy forest." %>
          <div class="space-y-1 col-span-2">
            <p class="drop-cap"><strong>TEA</strong> will be served after the meal, along with cakes (including lovely gluten free items) and a few other surprises.</p>
            <p>A full bar with custom cocktails will be available throughout the event.</p>
          </div>
        </div>
      </section>
      <section class="grid flex-col gap-4 card bg-paper max-w-screen-md odd:-rotate-[0.5deg] even:rotate-[0.5deg] even:self-end">
        <div class="space-y-1 text-center">
          <h2>There will be fantasy and merriment</h2>
          <p>And so we ask, who will you become? Who are you <em>really</em>?</p>
        </div>
        <h3 class="text-center text-xl uppercase tracking-wide font-display font-bold">Join a guild</h3>
        <%= form_for current_user, data: { controller: "form", action: "input->form#submit" } do |f| %>
          <div class="grid gap-1 sm:grid-cols-3 lg:grid-cols-5">
            <%= f.collection_radio_buttons :guild_id, Guild.where(secret: false), :id, :name do |g| %>
              <div class="guild-<%= g.object.name %> p-2 border rounded-none sm:text-center">
                <%= g.label(class: "max-sm:flex gap-4") do %>
                  <%= g.radio_button(class: "sr-only peer") %>
                  <%= image_tag(url_for(g.object.icon), class: "rounded-full size-20 sm:size-24 mx-auto") if g.object.icon.attached? %>
                  <div class="mt-1">
                    <h4 class="font-bold text-xl"><%= g.object.name %></h4>
                    <p class="text-pretty text-sm leading-tight"><%= g.object.description %></p>
                  </div>
                <% end %>
              </div>
            <% end %>
          </div>
        <% end %>
      </section>
    <% end %>
    <section class="flex flex-col gap-4 card bg-paper max-w-screen-md odd:-rotate-[0.5deg] even:rotate-[0.5deg] even:self-end">
      <div class="space-y-1 text-center">
        <h2>Adventuring Party</h2>
        <p>Your invitation may have been addressed to you or more. If you have additional guests, please add them that we may prepare for their arrival:</p>
      </div>

      <h4 class="border-b border-amber-800/20 mb-1">Other Party Members</h4>
      <%= render @party, guests: @additional_guests %>

      <%= form_for @party do |f| %>
        <div class="field">
          <%= f.label :notes, "Additional Notes" %>
          <%= f.text_area :notes, rows: 6, placeholder: "Please let us know anything additional, such as allergies or special accomodations, your party may need to join our adventure." %>
        </div>
        <% if @party.errors.any? %>
          <p class="text-red-700"><%= @party.errors.full_messages.to_sentence %></p>
        <% end %>
        <%= f.submit "Submit RSVP!", class: "text-lg btn primary mt-2 float-right" %>
      <% end %>
    </section>
  </div>
</div>

app/views/parties/show.html.erb
<div class="bg-cover bg-[url('backgrounds/castle.jpg')] min-h-screen grid place-content-center pt-40 pb-20 px-4">
  <div class="card md:text-xl space-y-5 text-center max-w-screen-lg">
    <h1>Thank you for your response!</h1>

    <% if @party.rsvp? %>
      <p class="text-balance">Keep an eye to your inbox, where we’ll update you with additional information including dress code inspiration, accommodation details, and more, in the near future.</p>

      <ul class="grid gap-y-8 gap-x-4 md:grid-cols-3 text-base text-left p-6">
        <li class="space-y-2">
          <h4 class="font-bold font-caption uppercase text-sm not-italic">What to wear</h4>
          <p class="leading-tight">First and foremost, be comfortable and express yourself. We encourage you to lean into your chosen guild's colors, and feel free to <%= link_to "peruse the realm's latest fashion trends", guilds_path, class: "underline decoration-dotted hover:decoration-solid" %> for inspiration.</p>
          <p class="leading-tight">We already know of various people intending to wear kilts, cocktail dresses, cloaks, and plate armor – do what you feel confident in, and inspires your sense of adventure.</p>
          <p class="text-balance leading-[1.1] p-2 font-bold border-l"><strong class="font-caption text-xs font-bold">TL;DR:</strong><em class="italic tracking-tight">“Creative Black Tie”, fantasy optional, anything but blue*</em></p>
          <p class="text-balance text-xs text-caption opacity-60">*We (the bride & groom) will be wearing blue.</p>
        </li>

        <li class="space-y-2">
          <h4 class="font-bold font-caption uppercase text-sm not-italic">Where to stay</h4>
          <p class="leading-tight text-pretty">We have blocks at two local hotels:</p>
          <ul class="space-y-1 indent-2 leading-tight">
            <li class="text-pretty">
              <h5 class="inline font-caption text-xs font-bold uppercase"><a class="underline decoration-dotted hover:decoration-solid" href="https://hotelrevivalbaltimore.com/">Hotel Revival</a>.</h5>
              <p class="inline">A trendy bastion in the historic part of the city – walking distance to museums, monuments, and eateries. Great for those looking to explore the city and its sights, and convenient for those arriving by train.</p>
            </li>

            <li class="text-pretty">
              <h5 class="inline font-caption text-xs font-bold uppercase"><a class="underline decoration-dotted hover:decoration-solid" href="https://www.marriott.com/">Delta by Marriot</a>.</h5>
              <p class="inline">Nestled in the village of Cross Keys, Delta boasts free parking, nearby shops and restaurants, and ample greenery. Great for those who want to be closer to the wedding venue, and escape the hustle and bustle of city life.</p>
            </li>
          </ul>
        </li>

        <li class="space-y-2 relative pb-10">
          <h4 class="font-bold font-caption uppercase text-sm not-italic">More to the story</h4>
          <p class="leading-tight">This is just the first step of the journey, and we’re so happy to have you coming along with us – <%= link_to "the realm", map_path, class: "underline decoration-dotted hover:decoration-solid" %> is full of adventures to be had.</p>
          <p class="leading-tight text-pretty">We have more to share soon, but if there any questions at all, feel free to reach out to either of us:</p>

          <ul>
            <li>— <a class="underline decoration-dotted hover:decoration-solid" href="mailto:bride@example.com">Marnie Williams</a></li>
            <li>— <a class="underline decoration-dotted hover:decoration-solid" href="mailto:nick@miniware.team">Nick Noble</a></li>
          </ul>

          <%= image_tag "props/seal-wax.png", class: "absolute right-0 bottom-0 size-24 rotate-6", alt: "A dark green wax seal depicting a magical lantern enreathed by flowers and eucalyptus." %>
        </li>

      </ul>

      <% unless @party.locked? %>
        <hr>
        <% deadline = @party.response_deadline %>
        <h4>In the meantime, here's what you submitted – feel free to update until <%= deadline.strftime("%B #{deadline.day.ordinalize}, %Y") %>:</h4>
      <% end %>

      <%= render @party %>
    <% else %>
    <div class="grid place-content-center">
      <%= render "shared/quick_links" %>
    </div>
    <% end %>
  </div>
</div>