config/routes.rb
Rails.application.routes.draw do
  unless Rails.env.development?
    get "/service-worker.js", to: "pwa#service_worker", as: :pwa_service_worker
    get "/manifest.json", to: "pwa#manifest", as: :pwa_manifest
  end

  passwordless_for :guests
  resources :guests

  get "RSVP", to: "parties#new" # in case of all caps
  get "rsvp", to: "parties#new", as: :new_party
  get "rsvp/step-2(/:id)", to: "parties#onboarding", as: :onboarding
  resource :party, except: [:new, :index, :destroy]
  resources :guilds, only: [:index, :show]

  get "registry", to: "infos#registry", as: :registry

  get "realm", to: "infos#map", as: :map
  get "map", to: "infos#map" # just in case people try it
  resources :locations, only: [:index]

  namespace :dungeon_master, path: "dm" do
    resources :parties
    resources :guilds
    resources :quests
    resources :guests
    resources :locations
    resources :mailings, only: [:index, :new, :show, :create]
    root "guests#index"
  end

  root "infos#home"
end

app/models/guest.rb
class Guest < ApplicationRecord
  include Feast

  belongs_to :party
  belongs_to :guild, optional: true
  has_and_belongs_to_many :achievements
  has_and_belongs_to_many :mailings

  scope :attending, -> { joins(:party).where(parties: {rsvp: true}) }

  passwordless_with :email
  normalizes :email, with: ->(email) { email.strip.downcase }

  validates :email,
    uniqueness: {case_sensitive: false, allow_blank: true},
    format: {with: URI::MailTo::EMAIL_REGEXP, allow_blank: true}

  normalizes :name, with: ->(name) { name.strip }
  validates :name, presence: true, uniqueness: {case_sensitive: false}
end

app/models/guest/feast.rb
module Guest::Feast
  extend ActiveSupport::Concern

  included do
    enum food_preference: {
      vegetarian: 0,
      duck: 1,
      salmon: 2,
      child: 3
    }
  end

  def feast
    case food_preference
    when "vegetarian"
      "Foraged (V)"
    when "duck"
      "Fowl (Duck)"
    when "salmon"
      "Fish (Salmon)"
    when "child"
      "Child's Feast"
    else
      "Feast TBD"
    end
  end
end

app/controllers/concerns/dungeon_master/cerberus.rb
module DungeonMaster::Cerberus
  extend ActiveSupport::Concern

  included do
    layout "dungeon_master"
    before_action :require_user!
    before_action :require_dm!
  end
end

app/controllers/dungeon_master/guests_controller.rb
class DungeonMaster::GuestsController < GuestsController
  include DungeonMaster::Cerberus

  def index
    @columns = {
      Name: :name,
      Party: "parties.name",
      Feast: :food_preference,
      Guild: "guilds.name",
      Notes: :notes
    }
    name = params[:name]&.downcase || ""
    sort = params[:sort] || "parties.name"
    @guests = Guest
      .joins(:party, :guild)
      .attending
      .order(sort => :asc)
      .where("lower(guests.name) LIKE ?", "%#{name}%")

    respond_to do |format|
      format.html
      format.turbo_stream
      format.csv {
        render_csv "#{Date.today.strftime("%Y-%m-%d")}-williams-noble-guests"
      }
    end
  end

  private

  def render_csv(filename = nil)
    filename ||= params[:action]
    filename += '.csv'

    if request.env['HTTP_USER_AGENT'] =~ /msie/i
      headers['Pragma'] = 'public'
      headers["Content-type"] = "text/plain"
      headers['Cache-Control'] = 'no-cache, must-revalidate, post-check=0, pre-check=0'
      headers['Content-Disposition'] = "attachment; filename=\"#{filename}\""
      headers['Expires'] = "0"
    else
      headers["Content-Type"] ||= 'text/csv'
      headers["Content-Disposition"] = "attachment; filename=\"#{filename}\""
    end

    render :layout => false
  end
end

app/controllers/dungeon_master/guilds_controller.rb
class DungeonMaster::GuildsController < ApplicationController
  include DungeonMaster::Cerberus

  before_action :set_guild, only: [:update, :edit]

  def index
    @guilds = Guild.all
  end

  def edit
  end

  def update
    if params[:remove_looks].present?
      params[:remove_looks].each do |id|
        attachment = ActiveStorage::Attachment.find_by(id: id)

        if attachment.present?
          attachment.purge
          # Remove the ID from the looks array
          params[:guild][:looks].reject! { |look| look == attachment.blob.signed_id }
        end
      end
    end

    if @guild.update(guild_params)
      flash[:notice] = "#{@guild.name} updated!"
      redirect_to edit_dungeon_master_guild_path(@guild)
    else
      flash[:error] = @guild.errors.full_messages.to_sentence
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def set_guild
    @guild = Guild.with_attached_looks.find_by(slug: params[:id])
  end

  def guild_params
    params.require(:guild).permit(:description, :secret, :icon, :background, looks: [])
  end
end

app/controllers/dungeon_master/locations_controller.rb
class DungeonMaster::LocationsController < ApplicationController
  include DungeonMaster::Cerberus

  before_action :set_location, only: [:show, :edit, :update, :destroy]

  def index
    @locations = Location.all
  end

  def show
  end

  def new
    @location = Location.new
  end

  def create
    @location = Location.new(location_params)
    if @location.save
      redirect_to dungeon_master_locations_path, success: "Location was successfully created."
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @location.update(location_params)
      redirect_to dungeon_master_locations_path, success: "Location was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @location.destroy
    redirect_to dungeon_master_locations_path, success: "Location was successfully destroyed."
  end

  private

  def set_location
    @location = Location.find(params[:id])
  end

  def location_params
    params.require(:location).permit(:name, :description, :address, :icon, :is_key)
  end
end

app/controllers/dungeon_master/mailings_controller.rb
class DungeonMaster::MailingsController < ApplicationController
  include DungeonMaster::Cerberus

  def index
    @mailings = Mailing.all
  end

  def show
    @mailing = Mailing.find(params[:id])
  end

  def new
    @mailing = Mailing.new
  end

  def create
    @mailing = Mailing.new(mailing_params)

    failed = []

    if @mailing.save
      Rails.logger.info "=== SENDING '#{@mailing.subject}'"

      @mailing.guests.each do |guest|
        Rails.logger.info "Sending to #{guest.name}..."
        if guest.email.blank?
          Rails.logger.info "skipping since they don't have an email"
          next
        end

        begin
          GuestMailer.info_email(@mailing, guest).deliver_now
          Rails.logger.info "SENT to #{guest.name}"
        rescue => e
          Rails.logger.error "Couldn't send due to error: #{e.message}"
          failed << guest.name
        end
      end
      Rails.logger.info "=== DONE SENDING"

      if failed.any?
        Rails.logger.error "FAILED SENDING: #{failed.join(", ")}"
        flash[:error] = "Failed to send to: #{failed.join(", ")}" if failed.any?
      else
        flash[:success] = "Sent to #{@mailing.guests.count} guests!"
      end

      redirect_to [:dungeon_master, @mailing]
    else
      flash[:error] = @mailing.errors.full_messages.to_sentence
      render :new, status: :unprocessable_entity
    end
  end

  private

  def mailing_params
    params.require(:mailing).permit(:subject, :body, guest_ids: [])
  end
end

app/controllers/dungeon_master/parties_controller.rb
class DungeonMaster::PartiesController < PartiesController
  include DungeonMaster::Cerberus
  before_action :set_party, only: [:show, :edit, :update, :destroy]

  def index
    @parties = Party.all
    @attending = Guest.attending
  end

  def show
  end

  def edit
  end

  def update
    if @party.update(party_params)
      redirect_to [:dungeon_master, @party], notice: "Party was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @party.destroy
    redirect_to [:dungeon_master, @party]
  end

  private

  def set_party
    @party = Party.find(params[:id])
  end

  def party_params
    params.require(:party).permit(
      :name,
      :rsvp,
      :notes,
      :response_deadline,
      guests_attributes: [
        :id,
        :name,
        :email,
        :under_13,
        :food_preference,
        :notes
      ]
    )
  end
end

app/controllers/dungeon_master/quests_controller.rb
class DungeonMaster::QuestsController < ApplicationController
  include DungeonMaster::Cerberus
  before_action :set_quest, only: [:show, :edit, :update, :destroy]

  def index
    @quests = Quest.all
  end

  def show
  end

  def new
    @quest = Quest.new
    render :edit
  end

  def create
    @quest = Quest.new(quest_params)
    if @quest.save
      flash.now[:success] = "Quest added!"

      render turbo_stream: [
        turbo_stream.append("quests", partial: "quest", locals: {quest: @quest}),
        helpers.render_flash_stream
      ]
    else
      flash[:error] = "Couldn't save this quest!"
      render :edit
    end
  end

  def edit
  end

  def update
    if @quest.update(quest_params)
      flash.now[:notice] = "Quest was successfully updated."

      render turbo_stream: [
        turbo_stream.update(@quest),
        helpers.render_flash_stream
      ]
    else
      flash[:error] = "Couldn't save this quest!"
      render :edit
    end
  end

  def destroy
    @quest.destroy
    flash[:notice] = "Quest removed"
    redirect_to dungeon_master_quests_url
  end

  private

  def set_quest
    @quest = Quest.find(params[:id])
  end

  def quest_params
    params.require(:quest).permit(:title, :description, :xp, :reward)
  end
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
  before_action :require_user!
  before_action :set_guest, only: [:show, :edit, :update, :destroy]

  def show
  end

  def new
    @guest = Guest.new(under_13: params[:under_13].present?)
    @guest.party = Party.find(params[:party_id]) if params[:party_id].present? && current_user.dungeon_master?
    @guest.party ||= current_user.party
  end

  def create
    @guest = Guest.new(guest_params)
    @guest.party ||= current_user.party
    @guest.under_13 = false if @guest.under_13.nil?

    validate_preferences

    if @guest.errors.empty? && @guest.save
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    validate_preferences
    # need to manually check for error because we add our own in certain cases (see validate_preferences)
    if @guest.errors.empty? && @guest.update(guest_params)
      flash[:success] = "Character saved!"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @guest.destroy
  end

  private

  def set_guest
    @guest = Guest.find(params[:id])
  end

  def validate_preferences
    if @guest != current_user
      unless guest_params[:food_preference].present?
        @guest.errors.add(:food_preference, "must be set")
      end

      unless guest_params[:guild_id].present?
        @guest.errors.add(:guild_id, "must be chosen")
      end
    end
  end

  def guest_params
    params.require(:guest)
      .permit(
        :name, :email, :under_13, :food_preference, :notes, :party_id, :guild_id
      )
  end
end

app/helpers/dungeon_master/guilds_helper.rb
module DungeonMaster::GuildsHelper
end

app/helpers/dungeon_master/parties_helper.rb
module DungeonMaster::PartiesHelper
end

app/helpers/dungeon_master/quests_helper.rb
module DungeonMaster::QuestsHelper
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/views/dungeon_master/guests/_guest.html.erb
<%= turbo_frame_tag dom_id(guest), class: "col-span-full grid grid-cols-subgrid items-baseline py-1 border-b" do %>
  <h4 class="font-bold"><%= guest.name %></h4>
  <p><%= guest.party.name %></p>
  <p class="capitalize"><%= guest.food_preference %></p>
  <p><%= guest.guild.name %></p>
  <p><%= guest.notes %></p>
  <nav class="flex justify-end gap-2">
    <%= link_to 'Edit', edit_dungeon_master_guest_path(guest), class: "text-indigo-600 hover:text-indigo-900" %>
    <!-- <%= link_to 'Delete', guest, method: :delete, data: { confirm: 'Are you sure?' }, class: "text-red-600 hover:text-red-900" %> -->
  </nav>
<% end %>

app/views/dungeon_master/guests/_stats.html.erb
<div class="grid grid-cols-2">

  <div class="prose w-1/3 prose-emerald">
    <table>
      <thead class="uppercase font-bold text-xs">
        <tr>
          <th>Feast</th>
          <th>Plates</th>
        </tr>
      </thead>
      <tbody>
        <% @attending.group_by(&:food_preference).each do |feast, guests| %>
          <tr>
            <td class="whitespace-nowrap"><%= guests.first.feast %></td>
            <td><%= guests.count %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <div class="prose w-1/3 prose-emerald">
    <table>
      <thead class="uppercase font-bold text-xs">
        <tr>
          <th>Guild</th>
          <th>Allegiance</th>
        </tr>
      </thead>
      <tbody>
        <% @attending.group_by(&:guild).each do |guild, guests| %>
          <tr>
            <td><%= guild&.name %></td>
            <td><%= guests.count %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>



</div>

app/views/dungeon_master/guests/edit.html.erb
<%= turbo_frame_tag dom_id(@guest), class: "" do %>
  <%= form_with model: [:dungeon_master, @guest], class: "contents *:self-end" do |f| %>
    <div class="field bg-paper p-1">
      <%= f.text_field :name, required: true %>
    </div>
    <div class="field bg-parchment-dark p-1">
      <%= f.collection_select :party_id, Party.all, :id, :name, { class: "block w-full" } %>
    </div>
    <div class="field bg-paper p-1">
      <% food_options = [['Foraged (V)', 'vegetarian'], ['Fowl (Duck)', 'duck'], ['Fish (Salmon)', 'salmon']] %>
      <% food_options.prepend(['Child’s Feast', 'child']) if @guest.under_13? %>
      <%= f.select :food_preference, food_options, class: "block w-full", prompt: "Wants to eat..." %>
    </div>
    <div class="field bg-paper p-1">
      <%= f.collection_select :guild_id, Guild.all, :id, :name, { include_blank: 'Select Guild' }, { class: "block w-full" } %>
    </div>
    <div class="field bg-paper p-1">
      <%= f.text_field :notes %>
    </div>
    <div class="actions flex justify-end">
      <%= f.submit class: "btn primary" %>
    </div>
  <% end %>
<% end %>

app/views/dungeon_master/guests/index.csv.erb
Name, Email, Party, Guild, Food Preference, Notes
<%=
CSV.generate do |csv|
  @guests.each do |guest|
    csv << [ guest[:name], guest[:email], guest.party[:name], guest.guild[:name], guest[:food_preference], guest[:notes] ]
  end
end.html_safe
%>

app/views/dungeon_master/guests/index.html.erb
<aside class="flex justify-between items-baseline">
<%= form_with url: dungeon_master_guests_path, method: :get, data: {
  turbo_frame: "guests",
  turbo_action: "advance",
  controller: "form",
  action: "input->form#submit"
} do |form| %>
  <%= form.search_field :name, placeholder: "Search by name...", value: params[:name] %>
<% end %>

  <%= link_to "Export CSV", dungeon_master_guests_path(format: :csv), class: "btn" %>
</aside>

<div class="w-full grid [grid-template-columns:repeat(6,minmax(min-content,100%))]">
  <header class="col-span-full grid grid-cols-subgrid border-b-2">
    <% @columns.each do |label, field| %>
      <%= link_to label, { sort: field }, { class: (params[:sort] == field.to_s ? 'font-bold' : ''), data: { turbo_action: 'replace', turbo_frame: label } } %>
    <% end %>
  </header>

  <%= turbo_frame_tag "guests", class: "contents" do %>
    <%= render @guests %>
  <% end %>
</div>