config/routes.rb
Rails.application.routes.draw do
  unless Rails.env.development?
    get "/service-worker.js", to: "pwa#service_worker", as: :pwa_service_worker
    get "/manifest.json", to: "pwa#manifest", as: :pwa_manifest
  end

  passwordless_for :guests
  resources :guests

  get "RSVP", to: "parties#new" # in case of all caps
  get "rsvp", to: "parties#new", as: :new_party
  get "rsvp/step-2(/:id)", to: "parties#onboarding", as: :onboarding
  resource :party, except: [:new, :index, :destroy]
  resources :guilds, only: [:index, :show]

  get "registry", to: "infos#registry", as: :registry

  get "realm", to: "infos#map", as: :map
  get "map", to: "infos#map" # just in case people try it
  resources :locations, only: [:index]

  namespace :dungeon_master, path: "dm" do
    resources :parties
    resources :guilds
    resources :quests
    resources :guests
    resources :locations
    resources :mailings, only: [:index, :new, :show, :create]
    root "guests#index"
  end

  root "infos#home"
end

app/models/location.rb
class Location < ApplicationRecord
  validates :name, :address, presence: true
  validates :address, uniqueness: {case_sensitive: true}

  geocoded_by :address
  after_validation :geocode, if: ->(obj) { obj.address.present? and obj.address_changed? }

  before_save :set_default_icon

  private

  def set_default_icon
    self.icon ||= "sign-post"
  end
end

app/controllers/concerns/dungeon_master/cerberus.rb
module DungeonMaster::Cerberus
  extend ActiveSupport::Concern

  included do
    layout "dungeon_master"
    before_action :require_user!
    before_action :require_dm!
  end
end

app/controllers/dungeon_master/guests_controller.rb
class DungeonMaster::GuestsController < GuestsController
  include DungeonMaster::Cerberus

  def index
    @columns = {
      Name: :name,
      Party: "parties.name",
      Feast: :food_preference,
      Guild: "guilds.name",
      Notes: :notes
    }
    name = params[:name]&.downcase || ""
    sort = params[:sort] || "parties.name"
    @guests = Guest
      .joins(:party, :guild)
      .attending
      .order(sort => :asc)
      .where("lower(guests.name) LIKE ?", "%#{name}%")

    respond_to do |format|
      format.html
      format.turbo_stream
      format.csv {
        render_csv "#{Date.today.strftime("%Y-%m-%d")}-williams-noble-guests"
      }
    end
  end

  private

  def render_csv(filename = nil)
    filename ||= params[:action]
    filename += '.csv'

    if request.env['HTTP_USER_AGENT'] =~ /msie/i
      headers['Pragma'] = 'public'
      headers["Content-type"] = "text/plain"
      headers['Cache-Control'] = 'no-cache, must-revalidate, post-check=0, pre-check=0'
      headers['Content-Disposition'] = "attachment; filename=\"#{filename}\""
      headers['Expires'] = "0"
    else
      headers["Content-Type"] ||= 'text/csv'
      headers["Content-Disposition"] = "attachment; filename=\"#{filename}\""
    end

    render :layout => false
  end
end

app/controllers/dungeon_master/guilds_controller.rb
class DungeonMaster::GuildsController < ApplicationController
  include DungeonMaster::Cerberus

  before_action :set_guild, only: [:update, :edit]

  def index
    @guilds = Guild.all
  end

  def edit
  end

  def update
    if params[:remove_looks].present?
      params[:remove_looks].each do |id|
        attachment = ActiveStorage::Attachment.find_by(id: id)

        if attachment.present?
          attachment.purge
          # Remove the ID from the looks array
          params[:guild][:looks].reject! { |look| look == attachment.blob.signed_id }
        end
      end
    end

    if @guild.update(guild_params)
      flash[:notice] = "#{@guild.name} updated!"
      redirect_to edit_dungeon_master_guild_path(@guild)
    else
      flash[:error] = @guild.errors.full_messages.to_sentence
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def set_guild
    @guild = Guild.with_attached_looks.find_by(slug: params[:id])
  end

  def guild_params
    params.require(:guild).permit(:description, :secret, :icon, :background, looks: [])
  end
end

app/controllers/dungeon_master/locations_controller.rb
class DungeonMaster::LocationsController < ApplicationController
  include DungeonMaster::Cerberus

  before_action :set_location, only: [:show, :edit, :update, :destroy]

  def index
    @locations = Location.all
  end

  def show
  end

  def new
    @location = Location.new
  end

  def create
    @location = Location.new(location_params)
    if @location.save
      redirect_to dungeon_master_locations_path, success: "Location was successfully created."
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @location.update(location_params)
      redirect_to dungeon_master_locations_path, success: "Location was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @location.destroy
    redirect_to dungeon_master_locations_path, success: "Location was successfully destroyed."
  end

  private

  def set_location
    @location = Location.find(params[:id])
  end

  def location_params
    params.require(:location).permit(:name, :description, :address, :icon, :is_key)
  end
end

app/controllers/dungeon_master/mailings_controller.rb
class DungeonMaster::MailingsController < ApplicationController
  include DungeonMaster::Cerberus

  def index
    @mailings = Mailing.all
  end

  def show
    @mailing = Mailing.find(params[:id])
  end

  def new
    @mailing = Mailing.new
  end

  def create
    @mailing = Mailing.new(mailing_params)

    failed = []

    if @mailing.save
      Rails.logger.info "=== SENDING '#{@mailing.subject}'"

      @mailing.guests.each do |guest|
        Rails.logger.info "Sending to #{guest.name}..."
        if guest.email.blank?
          Rails.logger.info "skipping since they don't have an email"
          next
        end

        begin
          GuestMailer.info_email(@mailing, guest).deliver_now
          Rails.logger.info "SENT to #{guest.name}"
        rescue => e
          Rails.logger.error "Couldn't send due to error: #{e.message}"
          failed << guest.name
        end
      end
      Rails.logger.info "=== DONE SENDING"

      if failed.any?
        Rails.logger.error "FAILED SENDING: #{failed.join(", ")}"
        flash[:error] = "Failed to send to: #{failed.join(", ")}" if failed.any?
      else
        flash[:success] = "Sent to #{@mailing.guests.count} guests!"
      end

      redirect_to [:dungeon_master, @mailing]
    else
      flash[:error] = @mailing.errors.full_messages.to_sentence
      render :new, status: :unprocessable_entity
    end
  end

  private

  def mailing_params
    params.require(:mailing).permit(:subject, :body, guest_ids: [])
  end
end

app/controllers/dungeon_master/parties_controller.rb
class DungeonMaster::PartiesController < PartiesController
  include DungeonMaster::Cerberus
  before_action :set_party, only: [:show, :edit, :update, :destroy]

  def index
    @parties = Party.all
    @attending = Guest.attending
  end

  def show
  end

  def edit
  end

  def update
    if @party.update(party_params)
      redirect_to [:dungeon_master, @party], notice: "Party was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @party.destroy
    redirect_to [:dungeon_master, @party]
  end

  private

  def set_party
    @party = Party.find(params[:id])
  end

  def party_params
    params.require(:party).permit(
      :name,
      :rsvp,
      :notes,
      :response_deadline,
      guests_attributes: [
        :id,
        :name,
        :email,
        :under_13,
        :food_preference,
        :notes
      ]
    )
  end
end

app/controllers/dungeon_master/quests_controller.rb
class DungeonMaster::QuestsController < ApplicationController
  include DungeonMaster::Cerberus
  before_action :set_quest, only: [:show, :edit, :update, :destroy]

  def index
    @quests = Quest.all
  end

  def show
  end

  def new
    @quest = Quest.new
    render :edit
  end

  def create
    @quest = Quest.new(quest_params)
    if @quest.save
      flash.now[:success] = "Quest added!"

      render turbo_stream: [
        turbo_stream.append("quests", partial: "quest", locals: {quest: @quest}),
        helpers.render_flash_stream
      ]
    else
      flash[:error] = "Couldn't save this quest!"
      render :edit
    end
  end

  def edit
  end

  def update
    if @quest.update(quest_params)
      flash.now[:notice] = "Quest was successfully updated."

      render turbo_stream: [
        turbo_stream.update(@quest),
        helpers.render_flash_stream
      ]
    else
      flash[:error] = "Couldn't save this quest!"
      render :edit
    end
  end

  def destroy
    @quest.destroy
    flash[:notice] = "Quest removed"
    redirect_to dungeon_master_quests_url
  end

  private

  def set_quest
    @quest = Quest.find(params[:id])
  end

  def quest_params
    params.require(:quest).permit(:title, :description, :xp, :reward)
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def index
    @locations = Location.all
    render json: @locations
  end
end

app/helpers/dungeon_master/guilds_helper.rb
module DungeonMaster::GuildsHelper
end

app/helpers/dungeon_master/parties_helper.rb
module DungeonMaster::PartiesHelper
end

app/helpers/dungeon_master/quests_helper.rb
module DungeonMaster::QuestsHelper
end

app/views/dungeon_master/locations/_form.html.erb
<%= form_with(model: [:dungeon_master, location], local: true, class: "space-y-4") do |form| %>
  <div class="field text-2xl">
    <%= form.label :name %>
    <%= form.text_field :name, required: true %>
  </div>
  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>
  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address, required: true %>
  </div>
  <div>
    <div class="field">
      <%= form.label :icon %>
      <%= form.text_field :icon, class: "font-mono" %>
    </div>
    <p class="italic opacity-40">Must be exact text, anything from <%= link_to "FontAwesome", "https://fontawesome.com/search?o=r&s=solid", class: "underline" %></p>
  </div>
  <div>
    <%= form.label :is_key, class: "flex gap-2 items-center" do %>
      <%= form.check_box :is_key, class: "accent-emerald-900" %> <p>This is a key location?</p>
    <% end %>
  </div>
  <div class="actions">
    <%= form.submit class: "btn primary" %>
  </div>
  <% if location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(location.errors.count, "error") %> prohibited this location from being saved:</h2>
      <ul>
        <% location.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<% end %>

app/views/dungeon_master/locations/edit.html.erb
<%= render "form", location: @location %>

app/views/dungeon_master/locations/index.html.erb
<script src="https://kit.fontawesome.com/a99b3f2249.js" crossorigin="anonymous"></script>
<%= link_to "Add a point of interest", new_dungeon_master_location_path, class: "btn self-start" %>
<div class="grid grid-ram gap-4">
  <% @locations.each do |location| %>
    <div class="location card space-y-2">
      <header>
        <i class="block text-sm fas fa-<%= location.icon %>"></i>
        <h3><%= location.name %></h3>
        <p><%= location.description %></p>
        <p><%= location.address %></p>
        <p class="text-xs font-mono"><%= location.latitude %> / <%= location.longitude %></p>
      </header>
      <hr>
      <nav class="flex gap-1 place-items-start">
        <%= link_to 'Edit', edit_dungeon_master_location_path(location), class: "btn primary pb-0 px-1 leading-none" %>
        <%= button_to 'Delete', dungeon_master_location_path(location), method: :delete, data: { turbo_confirm: 'Are you sure?' }, class: "btn pb-0 px-1 leading-none" %>
      </nav>
    </div>
  <% end %>
</div>

app/views/dungeon_master/locations/new.html.erb
<%= render "form", location: @location %>