config/routes.rb
Rails.application.routes.draw do
  unless Rails.env.development?
    get "/service-worker.js", to: "pwa#service_worker", as: :pwa_service_worker
    get "/manifest.json", to: "pwa#manifest", as: :pwa_manifest
  end

  passwordless_for :guests
  resources :guests

  get "RSVP", to: "parties#new" # in case of all caps
  get "rsvp", to: "parties#new", as: :new_party
  get "rsvp/step-2(/:id)", to: "parties#onboarding", as: :onboarding
  resource :party, except: [:new, :index, :destroy]
  resources :guilds, only: [:index, :show]

  get "registry", to: "infos#registry", as: :registry

  get "realm", to: "infos#map", as: :map
  get "map", to: "infos#map" # just in case people try it
  resources :locations, only: [:index]

  namespace :dungeon_master, path: "dm" do
    resources :parties
    resources :guilds
    resources :quests
    resources :guests
    resources :locations
    resources :mailings, only: [:index, :new, :show, :create]
    root "guests#index"
  end

  root "infos#home"
end

app/controllers/infos_controller.rb
class InfosController < ApplicationController
  def registry
    @og_image = "og-registry.jpg"
  end

  def home
  end

  def map
    @og_image = "og-map.jpg"
  end

  private

  def ward un, pw
    return if Rails.env.development?
    authenticate_or_request_with_http_basic do |username, password|
      username == un && password == pw
    end
  end
end

app/helpers/infos_helper.rb
module InfosHelper
end

app/views/infos/home.html.erb
<style>
  main {
    background-position: center center;
  }

  #main-navigation {
    background-image: radial-gradient(at bottom left, #0a504add, transparent);
    background-attachment: fixed;
    color: rgb(254 243 199);

    & a {
      line-height: 1;
      font-size: 2.8rem;

      @media (min-width: 768px) {
        /* 6xl */
        font-size: 3.75rem;
      }

      /* Fix leading */
      margin-top: 0.5rem;
      padding-bottom: 0.25rem;

      &:hover {
        font-style: italic;
      }
    }
  }
</style>
<main class="grid bg-cover bg-[url('backgrounds/castle.jpg')] min-h-screen">
  <nav id="main-navigation" class="flex flex-col justify-end items-start p-4 gap-1">
    <% if current_user %>
      <h5 class="text-white text-xl mb-3 leading-none">
        Welcome <%= current_user.name %>!<br>
        <span class="font-bold italic leading-tight">Choose your path:</span></h5>

      <%= link_to "DM Screen", dungeon_master_root_path if current_user&.dungeon_master? %>

      <% if current_user.party.rsvp?  %>
        <%= link_to "Adventuring Party", party_path %>
        <%= link_to "Map of the Realm", map_path, data: { turbo: false } %>
      <% end %>
    <% else %>
      <h5 class="text-white italic leading-tight text-xl font-bold mb-3">Choose your path:</h5>
      <%= link_to "RSVP", new_party_path %>
    <% end %>
    <%= link_to "Registry", registry_path %>
    <%= link_to "Guilds", guilds_path if current_user %>
    <%= auth_link %>
  </nav>
</main>

app/views/infos/map.html.erb
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css" integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY=" crossorigin=""/>
<script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js" integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo=" crossorigin=""></script>
<script src="https://kit.fontawesome.com/a99b3f2249.js" crossorigin="anonymous"></script>
<div class="relative h-dvh w-screen">
  <h1 class="absolute top-8 left-8 font-bold z-50 text-emerald-900">The Realm</h1>
  <div id="map" class="h-full w-full bg-amber-900 relative z-10"></div>
</div>
<script>
  const options = {
     zoomControl: false,
     attributionControl: false
  }

  const baltimore = [39.3403478,-76.6217985];
  const map = L.map('map', options).setView(baltimore, 12).setMaxZoom(16);

  // Watercolor base
  L.tileLayer('https://tiles.stadiamaps.com/tiles/stamen_watercolor/{z}/{x}/{y}.jpg', { maxZoom: 16 }).addTo(map);

  // Text Labels
  L.tileLayer('https://{s}.basemaps.cartocdn.com/light_only_labels/{z}/{x}/{y}{r}.png', {
  	  subdomains: 'abcd',
  	  maxZoom: 10
  }).addTo(map);

  function customIcon(name, highlighted=false) {
    const colors = highlighted ?
        "text-blue-800 hover:text-blue-600 z-50"
      : "text-rose-900 hover:text-rose-700 z-40"
    return  L.divIcon({
        html: `
          <div class="relative h-full w-full grid text-center items-end ${colors} transition-colors">
            <i class="text-xl fas fa-${name} drop-shadow"></i>
          </div>
        `,
        iconSize: [30, 42],
        iconAnchor: [15, 42]
    });
  }

  // POPULATE
  fetch('/locations')
    .then(response => response.json())
    .then(data => {
      data.forEach(location => {
        const marker = L.marker(
          [location.latitude, location.longitude],
          { icon: customIcon( location.icon, location.is_key )}
        ).addTo(map);
        marker.bindPopup(`
          <div class="space-y-1 card py-2 w-full">
            <header>
              <i class="block text-xl fas fa-${location.icon}"></i>
              <h3>${location.name}</h3>
              <p>${location.description}</p>
            </header>

            <footer class="border-t border-amber-950/5 pt-1">
              <p class="inline">Open in:</p>
              <nav class="inline-flex gap-1">
                <a href="https://www.google.com/maps/search/?api=1&query=${location.latitude},${location.longitude}" target="_blank">Google Maps</a> /
                <a href="http://maps.apple.com/?ll=${location.latitude},${location.longitude}&q=Dropped%20Pin" target="_blank">Apple Maps</a>
              </nav>
            </footer>
          </div>
        `);
      });
    });
</script>
<style>
  /* RESETS */
  .leaflet-container { font: unset; }
  .leaflet-div-icon{
    border: none;
    background: transparent;
    transform: translateY(20%);
  }
  .leaflet-popup-content-wrapper {
    background: unset;
    padding: 0;
    box-shadow: unset;
    border-radius: unset;
    width: max-content;
  }
  .leaflet-popup-content {
    margin: unset
  }

  .leaflet-popup-content p { margin: unset }


  /* CHANGES */
  .leaflet-popup { margin-bottom: 32px; }
  .leaflet-popup-close-button{
    top: 8px !important;
    right: 8px !important;
  }
  .leaflet-popup-tip {
    background-color: #e6d4ae;
  }
</style>

app/views/infos/registry.html.erb
<div class="bg-cover bg-fixed bg-[url('backgrounds/grotto.jpg')] min-h-screen grid place-content-center py-40 pb-[100dvh] px-4">
  <section class="card md:text-xl space-y-4 py-8 w-screen max-w-screen-md mx-auto">
    <div class="max-w-[40ch] space-y-4 mx-auto">
      <h1 class="text-center">What we want most</h1>
      <p class="leading-tight text-2xl text-balance">Your presence and support in our lives is the greatest gift we could ever hope for.</p>
      <p class="leading-tight">Many friends and relatives have asked for our registry – a list of things we might want in order to start this new chapter.</p>
      <p class="leading-tight">We looked at the things people traditionally put on this list, and found (as 30-somethings who'd both lived alone for some time) that we already had most of it.</p>
      <p class="leading-tight">Honestly, there's no appliance, luggage, glassware, bath towel, monogrammed robe, or sofa that we'd want, and could also fit into our tiny Brooklyn apartment. We don't want stuff!</p>
    </div>
    <div class="max-w-[40ch] space-y-4 mx-auto">
      <hr>
      <p class="leading-tight">By traveling from far away lands, and supporting us each in becoming the people we needed to be to meet each other, you've already given us something profound.</p>
       <%= image_tag "props/seal-wax.png", class: "mx-auto size-24 rotate-4 mt-6 mb-4" %>
      <p class="leading-tight text-center text-balance italic tracking-tight">Thank you for your presence in our lives.</p>
    </div>
  </section>
  <blockquote class="max-w-[40ch] mt-24 rounded-lg p-8 shadow-2xl shadow-amber-300 bg-blue-950/40 backdrop-blur-sm flex flex-col gap-3 mx-auto leading-tight text-balance text-center font-caption text-amber-100 drop-shadow-sm">
    <p>We put a poem here.</p>
    <p>You could too.</p>
    <p>For us, it summed up our feelings;</p>
    <p>About life, about beauty, about what we want most.</p>
    <p>I've removed it, even though it's one you've likely read before.</p>
    <p>Because you probably have a better option.</p>
    <p><strong>And this one was ours.</strong></p>
    <cite class="uppercase not-italic mt-1 font-bold font-sans text-[10px]">— Some wise person</cite>
  </blockquote>
</div>